Repository fgtclb/academic-extensions, pull requests merged in 2025-04, with the labels that each got.

#77 [BUGFIX] Ensure created error responses are really returned
  packages/fgtclb/academic-persons-edit/Classes/Controller/ProfileController.php
Labels: 1.x-up-port

#79 [BUGFIX] Use suiting translation keys in TCA
  packages/fgtclb/academic-persons/Configuration/TCA/tx_academicpersons_domain_model_contract.php
  packages/fgtclb/academic-persons/Resources/Private/Language/locallang_tca.xlf
Labels: bug, backport-1.x

#78 [BUGFIX] Adopt required contacts handling changes for TYPO3 requirements (`contacts4pages`)
  Build/phpstan/Core12/phpstan-baseline.neon
  Build/phpstan/Core13/phpstan-baseline.neon
  packages/fgtclb/academic-contact4pages/Classes/Domain/Repository/ContactRepository.php
  packages/fgtclb/academic-contact4pages/Configuration/TCA/Overrides/pages.php
  packages/fgtclb/academic-contact4pages/Configuration/TCA/Overrides/tx_academicpersons_domain_model_contract.php
  packages/fgtclb/academic-contact4pages/Configuration/TCA/tx_academiccontacts4pages_domain_model_contact.php
Labels: bug, backport-1.x, needs-tests

#86 [BUGFIX] Display assigned hidden system categories in backend views
  packages/fgtclb/academic-partners/Resources/Private/Backend/Partials/PageLayout/Doktype40.html
  packages/fgtclb/academic-programs/Resources/Private/Backend/Partials/PageLayout/Doktype20.html
  packages/fgtclb/academic-projects/Resources/Private/Backend/Partials/PageLayout/Doktype30.html
  packages/fgtclb/typo3-category-types/Classes/Domain/Model/Category.php
  packages/fgtclb/typo3-category-types/Classes/Domain/Repository/CategoryRepository.php
  packages/fgtclb/typo3-category-types/Classes/ViewHelpers/Be/CategoryViewHelper.php
Labels: bug, needs-tests

#87 [BUGFIX] Restore selected pages plugin setting handling
  packages/fgtclb/academic-partners/Classes/Factory/DemandFactory.php
  packages/fgtclb/academic-partners/Configuration/TCA/Overrides/tt_content.php
  packages/fgtclb/academic-programs/Classes/Factory/DemandFactory.php
  packages/fgtclb/academic-programs/Configuration/TCA/Overrides/tt_content.php
  packages/fgtclb/academic-projects/Classes/Factory/DemandFactory.php
  packages/fgtclb/academic-projects/Configuration/TCA/Overrides/tt_content.php
Labels: bug, needs-tests

#90 [TASK] Optimize geocoding in `academic_partners`
  .gitignore
  packages/fgtclb/academic-partners/Classes/Command/GeocodeCommand.php
  packages/fgtclb/academic-partners/Classes/Domain/Repository/PartnerRepository.php
  packages/fgtclb/academic-partners/Classes/Task/GeocodeTask.php
  packages/fgtclb/academic-partners/Resources/Private/Language/de.locallang_be.xlf
  packages/fgtclb/academic-partners/Resources/Private/Language/locallang_be.xlf
  packages/fgtclb/academic-partners/ext_localconf.php
Labels: needs-tests

#92 [FEATURE] Introduce `remove` and `useExisting` category type options
  packages/fgtclb/typo3-category-types/Classes/Loader/CategoryTypeLoader.php
Labels: needs-tests
